// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG55g6_wvv0g9fzPaQUf94I3D6I9MEUtQ',
    appId: '1:227986853129:web:5145bc2368ac81622957d8',
    messagingSenderId: '227986853129',
    projectId: 'simple-mail-eeb17',
    authDomain: 'simple-mail-eeb17.firebaseapp.com',
    storageBucket: 'simple-mail-eeb17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVoHmx0Pp9jLV8GdIdxxcEgjArEhvD6pc',
    appId: '1:227986853129:android:d80bc5f1bb4f49b82957d8',
    messagingSenderId: '227986853129',
    projectId: 'simple-mail-eeb17',
    storageBucket: 'simple-mail-eeb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOIj-WXujoehZEgeXFLCgfLY8hJgM1Uo',
    appId: '1:227986853129:ios:4a97608c152d19402957d8',
    messagingSenderId: '227986853129',
    projectId: 'simple-mail-eeb17',
    storageBucket: 'simple-mail-eeb17.appspot.com',
    androidClientId: '227986853129-3hpqq90kepsgrgpse0s2cd2urcv5086d.apps.googleusercontent.com',
    iosClientId: '227986853129-uesmkj2omj6ghou01199c0q919ljelda.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOIj-WXujoehZEgeXFLCgfLY8hJgM1Uo',
    appId: '1:227986853129:ios:4a97608c152d19402957d8',
    messagingSenderId: '227986853129',
    projectId: 'simple-mail-eeb17',
    storageBucket: 'simple-mail-eeb17.appspot.com',
    androidClientId: '227986853129-3hpqq90kepsgrgpse0s2cd2urcv5086d.apps.googleusercontent.com',
    iosClientId: '227986853129-uesmkj2omj6ghou01199c0q919ljelda.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG55g6_wvv0g9fzPaQUf94I3D6I9MEUtQ',
    appId: '1:227986853129:web:e48a2af6f447b0dc2957d8',
    messagingSenderId: '227986853129',
    projectId: 'simple-mail-eeb17',
    authDomain: 'simple-mail-eeb17.firebaseapp.com',
    storageBucket: 'simple-mail-eeb17.appspot.com',
  );

}